import Footer from "../../components/Footer/Footer";
import Slider from "../../components/Top/Slider/Slider";
import "./globals.css";

export const metadata = {
  title: "Fastcoding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        < Slider/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
